[project]
name = "fittex"
version = "0.1.0"
description = "HackUDC 2025 project for InditexTech"
readme = "README.md"
requires-python = "==3.12.7"
dependencies = [
    "ollama>=0.4.7",
    "requests>=2.32.3",
]
