[project]
name = "fittex"
version = "0.1.0"
description = "FitTeX project for InditexTech challenge at HackUDC 2025"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dynaconf>=3.2.10",
    "loguru>=0.7.3",
    "ollama>=0.4.7",
    "unsloth>=2025.2.15",
]
